import { Inter } from 'next/font/google';
import './globals.scss';
import Navigation from '@/components/navigation/navigation';
import Footer from '@/container/footer/footer';

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '800', '700'],
});

export const metadata = {
  title: 'Adams Abdulmaleek',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
