import { Inter } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';
import './globals.scss';
import clsx from 'clsx';

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '800', '700'],
});

export const metadata = {
  title: 'Adams Abdulmaleek',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={clsx(inter.className)}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
