import { ThemeProvider } from '@/components/ThemeContext';
import Navigation from '@/components/navigation/navigation';
import Footer from '@/container/footer/footer';

export const metadata = {
  title: 'Adams Abdulmaleek',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider >
      <Navigation />
      {children}
      <Footer />
    </ThemeProvider>
  );
}
